require 'jars/installer'

task :install_jars do
    Jars::Installer.vendor_jars!
end

namespace :run do
    [:catbot, :pingbot, :compositebot].each do |bot|
        task bot do
            ruby "-J-Dorg.slf4j.simpleLogger.defaultLogLevel=debug lib/#{bot}.rb"
        end
    end
end

